name: ioHook

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest
    strategy:
      fail-fast: false		
      max-parallel: 15
      matrix:
        python: [3.6, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Use Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
      env:
        PYTHON_VERSION: ${{ matrix.python }}
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm install
    - run: npm run build